spring:
  datasource:
    url: jdbc:mysql://vaio:3306/first_db?useSSL=false
    username: root
    password: zzzzzz
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    # 设置当应用启动时总是初始化Spring Batch数据库，默认只有嵌入式数据库才会初始化数据库
    initialize-schema: always
    job:
      # 关闭任务自动执行，默认为自动执行
      enabled: false
