server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka:123456@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

