##########################################################
# 通用配置
##########################################################
spring:
  # DataSource Config
  datasource:
    # 连接池配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: itplhHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # H2 Config
  h2:
    console:
      # 开启web console功能
      enabled: true
      # 默认 /h2-console
      path: /h2

# Mybatis Plus Config
mybatis-plus:
  mapper-locations: classpath*:com/itplh/sdk/**/xml/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
