##########################################################
# 开发环境
##########################################################
server:
  port: 8758

spring:
  # 引入通用配置
  profiles:
    include:
      - common
  # DataSource Config
  datasource:
    driver-class-name: org.h2.Driver
    # 配置h2数据库的连接地址
    url: jdbc:h2:D:/code/tp-practice/sdk-server/data/sdk_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;MODE=MYSQL;
    username: itplh
    password: VB8yzXg4vsW8tGPU

# Mybatis Plus Config
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
