security:
  oauth2:
    client:
      client-id: itplh-client2
      client-secret: itplh-client-secret2
      user-authorization-uri: http://127.0.0.1:8888/sso-server/oauth/authorize
      access-token-uri: http://127.0.0.1:8888/sso-server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:8888/sso-server/oauth/token_key

server:
  port: 8082
  context-path: /client2

