security:
  oauth2:
    client:
      client-id: itplh-client2
      client-secret: itplh-client-secret2
      user-authorization-uri: http://sso.itplh.com:8888/oauth/authorize
      access-token-uri: http://sso.itplh.com:8888/oauth/token
    resource:
      jwt:
        key-uri: http://sso.itplh.com:8888/oauth/token_key

server:
  port: 8082

