spring:
  application:
    name: eurekaserver

server:
  port: 8760

eureka:
  instance:
    hostname: peer8760
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer8761:8761/eureka/
