spring:
  profiles:
#    active: cost-time
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local81:3306/itplh-security-demo?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root

  session:
    store-type: none

  redis:
    host: local81
    port: 6379

#security:
#  basic:
#    enabled: false

## 应用级配置
#itplh:
#  security:
#    browser:
#       # 自定义登录页
#      loginPage: /demo-sign-in.html
#      loginType: REDIRECT
#    # 图片验证码相关
#    code:
#      image:
#        length: 6
#        width: 100
